### ISSUE TITLE
[SUGGESTION] Don't upload to MEGA.

### ISSUE THREAD

**Issue by NathanDreamweaver** [rakisaionji/FrankenToneArcade#1]
Due to the fact that the mod will only ever increase in size, i would highly suggest not using MEGA but rather something else, due to the bandwith limit MEGA has for free users.

**Comment by rakisaionji** [comment]
Oy vey. This is not an issue tho. Thank you for your suggestion anyway. But you know, you already had AFT, why bother with this trash anyway?

Btw my modpack release will be modular and incremental. Like what mdata is rolled out on ALL.net anyway. If you don't have last packs, you cannot install new pack. That's all.

And big releases (milestones) of course will be on torrents tho.

**Comment by NathanDreamweaver** [comment]
Ah i see. Simply wanted to be as helpful as i could, that is all. However i don't really find myself able to suggest torrents either. Torrents are really bad for preservation, so while they may work right now, there is a chance of one of them becoming forever seedless.

**Comment by rakisaionji** [comment]
So which sites you suggest? List them out and I'll consider.

**Comment by cainan-c** [comment]
Preferably something like Google Drive, Mediafire, Dropbox or Zippyshare (Although that's currently banned in the United Kingdom). The only concern is storage space on these cloud platforms

**Comment by lybxlpsv** [comment]
As long as the all db stuff/files needed to get it working assuming user has ps4 repacked and retargeted to ac files, pv_db, pv_field, 2d sel stuff and gm pv list is on the repo it should be preserved since players can just dump ps4 ver and use automated tools to "frankenstein" his pda into ft and then copy all db and 2d stuff into pda from this repo.
That way updates are way easier too assuming you only do FT pvs and not other diva games.

**Comment by NathanDreamweaver** [comment]
Google Drive would be great but honestly i suggest anything which isn't Mega, torrent or any website that requires a premium account to download at an higher speed than 10 kb/s.

**Comment by rakisaionji** [comment]
Okay then. Thank you everyone. I will upload my databases in XML format, not binary, soon here. (Those are already in my private repo tho).

I may also reupload the first pack to Google Drive when I release another pack in the summer.

**Comment by Cainan-Corlett** [comment]
https://drive.google.com/file/d/1btv4xIyah-uBCG1Z-bgUZupuqCwIhM7w/view?usp=sharing

**Comment by nastys** [comment]
You could create a channel on Telegram and upload the files there. It's fast, free, and unlimited.
https://telegram.org/faq_channels

**Comment by rakisaionji** [comment]
Goodbye everyone. And fuck **PKBowsy**.

**Comment by nastys** [comment]
> 
> 
> Goodbye everyone. And fuck **PKBowsy**.

Actually, you did get credited by PKBowsy in one of the comments.
https://www.youtube.com/watch?v=mDRLYJtl3SU&lc=Ugz1z2kUDYJwBpvxtb14AaABAg.8uCDueZpVEE8uCFgodGjWx

That's how I found this repo (although a link in the description would've been preferrable).

**Comment by cainan-c** [comment]
> > Goodbye everyone. And fuck **PKBowsy**.
> 
> Actually, you did get credited by PKBowsy in one of the comments.
> https://www.youtube.com/watch?v=mDRLYJtl3SU&lc=Ugz1z2kUDYJwBpvxtb14AaABAg.8uCDueZpVEE8uCFgodGjWx
> 
> That's how I found this repo (although a link in the description would've been preferrable).

Where was he credited? I looked through all the comments and saw fuck all
And when asked about why he didn't credit? He said this
![image](https://user-images.githubusercontent.com/30056568/57110300-01595400-6d30-11e9-857c-a4b76d8376f7.png)

**Comment by nastys** [comment]
Click on the link, it should show that comment at the top.
