### ISSUE TITLE
2 songs missing

### ISSUE THREAD

**Issue by SiLPHER401** [rakisaionji/FrankenToneArcade#4]
2 songs missing :
1. pv_001 恋は戦争（love is war）
2. pv_002 ワールドイズマイン（world is mine）

Some possible reason :
1. reached the limit number of songs ?
2. some pv have data conflict with these two songs ?
3. some important data of the pv been accidentally deleted ?

Please tell me the answer for the missing song and fix it if possible. thank you.

**Comment by rakisaionji** [comment]
It's because of the fucked up encoding in the dbs. Please check if your `pv_db.txt` is UTF-8 without BOM or not. And make sure that every line is finished with `\n` (UNIX style) instead of `\r\n` (Windows) or `\r` (Mac).
