### ISSUE TITLE
[SUGGESTION] Add skins from the FTA

### ISSUE THREAD

**Issue by ghost** [rakisaionji/FrankenToneArcade#5]
Hello. I would like to see the textures of the skins that are presented in this image. Is it possible? Thank you ;)
![Skins FTA](https://user-images.githubusercontent.com/49981274/56736332-8eb90900-6770-11e9-9566-c1de8b2e7f61.png)

**Comment by BINiPad1999** [comment]
But if the skin added, how can you activate that skin ?

**Comment by ghost** [comment]
I need only the texture of these skins in good quality.  I don't need them to play

**Comment by rakisaionji** [comment]
I have seen your request on Discord. Planned to send you but well, I have to take down everything. You can blame PKBowsy for all this.
